// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
)

type Admin struct {
	ID             int32
	Email          string
	Password       string
	Name           string
	OrganizationID int32
	// Là root admin
	IsRootAdmin sql.NullBool
	// Đã thay đổi mật khẩu
	HaveChangePassword sql.NullBool
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
	DeletedAt          sql.NullTime
}

type AuthzAction struct {
	ID int32
	// Tên hành động
	Name string
	// Mô tả
	Description string
	// Là hành động cấp tổ chức
	IsOrganizationLevel sql.NullBool
	// Là hành động cấp facility
	IsFacilityLevel sql.NullBool
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	DeletedAt       sql.NullTime
}

type AuthzAdminPermission struct {
	ID           int32
	AdminID      int32
	PermissionID int32
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullTime
}

type AuthzAdminRole struct {
	ID        int32
	AdminID   int32
	RoleID    int32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}

type AuthzObject struct {
	ID int32
	// Tên authorization object
	Name string
	// Mô tả
	Description string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type AuthzPermission struct {
	ID        int32
	ObjectID  int32
	ActionID  int32
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}

type AuthzRole struct {
	ID int32
	// Tên vai trò
	Name string
	// Mã đơn vị
	OrganizationID int32
	// Mã facility
	FacilityID sql.NullInt32
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
	DeletedAt  sql.NullTime
}

type AuthzRolePermission struct {
	ID           int32
	RoleID       int32
	PermissionID int32
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullTime
}

type Facility struct {
	ID             int32
	Name           string
	Rating         sql.NullFloat64
	OrganizationID int32
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	DeletedAt      sql.NullTime
}

type Organization struct {
	ID int32
	// Tên đơn vị
	Name string
	// Số điện thoại
	Phone string
	// Email
	Email     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}
