// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package database

import (
	"context"
	"database/sql"
)

const createFacility = `-- name: CreateFacility :exec
INSERT INTO facilities (name, organization_id) VALUES (?, ?)
`

type CreateFacilityParams struct {
	Name           string
	OrganizationID int32
}

func (q *Queries) CreateFacility(ctx context.Context, arg CreateFacilityParams) error {
	_, err := q.db.ExecContext(ctx, createFacility, arg.Name, arg.OrganizationID)
	return err
}

const getFacilities = `-- name: GetFacilities :many
SELECT id, name, rating, organization_id, created_at, updated_at, deleted_at 
FROM facilities
WHERE 
    1 = 1
    AND (? IS NULL OR rating <= ?)
    AND (? IS NULL OR rating >= ?)
    AND (? IS NULL OR organization_id = ?)
`

type GetFacilitiesParams struct {
	LteRating      sql.NullFloat64
	GteRating      sql.NullFloat64
	OrganizationID sql.NullInt32
}

func (q *Queries) GetFacilities(ctx context.Context, arg GetFacilitiesParams) ([]Facility, error) {
	rows, err := q.db.QueryContext(ctx, getFacilities,
		arg.LteRating,
		arg.LteRating,
		arg.GteRating,
		arg.GteRating,
		arg.OrganizationID,
		arg.OrganizationID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Facility
	for rows.Next() {
		var i Facility
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Rating,
			&i.OrganizationID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFacilityByID = `-- name: GetFacilityByID :one
SELECT id, name, rating, organization_id, created_at, updated_at, deleted_at FROM facilities WHERE id = ?
`

func (q *Queries) GetFacilityByID(ctx context.Context, id int32) (Facility, error) {
	row := q.db.QueryRowContext(ctx, getFacilityByID, id)
	var i Facility
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Rating,
		&i.OrganizationID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateFacility = `-- name: UpdateFacility :exec
UPDATE facilities 
SET 
    name = coalesce(?, name), 
    organization_id = coalesce(?, organization_id) 
WHERE id = ?
`

type UpdateFacilityParams struct {
	Name           sql.NullString
	OrganizationID sql.NullInt32
	ID             int32
}

func (q *Queries) UpdateFacility(ctx context.Context, arg UpdateFacilityParams) error {
	_, err := q.db.ExecContext(ctx, updateFacility, arg.Name, arg.OrganizationID, arg.ID)
	return err
}
