APP_NAME = server
GOOSE_DRIVER ?= mysql
GOOSE_DBSTRING="root:password@tcp(127.0.0.1:3306)/golf_booking?multiStatements=true"
GOOSE_MIGRATION_DIR=./migrations
GOOSE_TABLE=goose_migrations

run:
	go run ./cmd/${APP_NAME}/
up:
	@GOOSE_DRIVER=${GOOSE_DRIVER} GOOSE_DBSTRING=${GOOSE_DBSTRING} GOOSE_MIGRATION_DIR=${GOOSE_MIGRATION_DIR} GOOSE_TABLE=${GOOSE_TABLE} goose -dir=${GOOSE_MIGRATION_DIR} up
down:
	@GOOSE_DRIVER=${GOOSE_DRIVER} GOOSE_DBSTRING=${GOOSE_DBSTRING} GOOSE_MIGRATION_DIR=${GOOSE_MIGRATION_DIR} GOOSE_TABLE=${GOOSE_TABLE} goose -dir=${GOOSE_MIGRATION_DIR} down

.PHONY: run up down
